### ISSUE TITLE
The Nostr.me OAuth window don't popup

### ISSUE THREAD

**Issue by ssakone** [erskingardner/nostr-ignition#2]
After fill the username and choose the domain, nothing more happen, and theres no errror in console, the OAuth window don't popup as well
![image](https://github.com/erskingardner/nostr-ignition/assets/39985611/73a52072-c521-4787-a98d-3adfffae1335)

**Comment by erskingardner** [comment]
I think that it's actually nostr.me that is down. I've pinged @pablof7z on that and, in the meantime, I added a timeout function in [7063bb7](https://github.com/erskingardner/nostr-ignition/commit/7063bb7b7f063a8edc6bd43c656e11b5171d70e9) to show an error message in the case that we don't get a response within 7 seconds.

**Comment by pablof7z** [comment]
the right way to do this is to send a `ping` request before displaying a provider as part of the validations being done along with the NIP-05 root, etc
